### ISSUE TITLE
PlatformIO Fails Compile

### ISSUE THREAD

**Issue by JDMarc** [Jaimi5/LoRaChat#10]
Was trying to compile a config for a ttgo-lora32-v1 and there appears to be many dependency errors that cause PlatformIO to fail compilation.
Even upon editing the .ini file to include the older versions of the dependencies it appears to not help the problem whatsoever as the program appears to overwrite those dependencies with newer (broken) versions.
Some examples of errors I got:
`src/config.h:128:13: error: 'LED_BUILTIN' was not declared in this scope
 #define LED LED_BUILTIN
             ^~~~~~~~~~~
src/helpers/helper.h:13:75: note: in expansion of macro 'LED'
     static void ledBlink(uint8_t times, uint16_t delayTime, uint8_t pin = LED);
                                                                           ^~~
src/config.h:128:13: error: 'LED_BUILTIN' was not declared in this scope
 #define LED LED_BUILTIN
             ^~~~~~~~~~~
src/helpers/helper.h:13:75: note: in expansion of macro 'LED'
     static void ledBlink(uint8_t times, uint16_t delayTime, uint8_t pin = LED);
                                                                           ^~~
*** [.pio\build\esp-wrover-kitNAYAD_V1R2\src\bluetooth\bluetoothCommandService.cpp.o] Error 1
*** [.pio\build\esp-wrover-kitNAYAD_V1R2\src\bluetooth\bluetoothService.cpp.o] Error 1`

`Library Manager: Installing dok-net/ghostl @ ^1.0.0
Library Manager: Warning! Could not install `{'owner': 'dok-net', 'name': 'ghostl', 'version': '^1.0.0'}` dependency for the`EspSoftwareSerial` package`

If anyone could possibly send me a pre-compiled file for the Lora32 V1 that would be greatly appreciated.

**Comment by Jaimi5** [comment]
Hi!
I have updated a new version. It seams that EspSoftwareSerial and ghostl library have changed something about their repositories.
Hope now it works correctly!

**Comment by JDMarc** [comment]
It would appear as though this has fixed the problem, thank you!
