### ISSUE TITLE
Bluetooth module not properly initializing

### ISSUE THREAD

**Issue by JDMarc** [Jaimi5/LoRaChat#11]
I was attempting to flash my lora32 board, which went successfully, but when I went to my phone to connect to the board over a Bluetooth serial terminal the board was nowhere to be found (I did enable bluetooth in the config file) I installed meshtastic to the board, assuming I had a faulty bluetooth module, but it appears the module is functional.
Some data to note:
Board: LilyGo LoRa32 V2.1_1.6
Bluetooth initialization output from board to serial: 
`[  5408][V][bluetoothService.cpp:66] initBluetooth(): [BluetoothService] Bluetooth callback registered`
`[  5955][I][BluetoothSerial.cpp:685] _init_bt(): device name set`
`[  5956][V][bluetoothService.cpp:75] initBluetooth(): [BluetoothService] DeviceID: 6f84`
`[  5955][I][BluetoothSerial.cpp:571] esp_bt_gap_cb(): ESP_BT_GAP_CONFIG_EIR_DATA_EVT: stat:0 num:4`
All else seems to initialize fine aswell, but as I don't have access to an mqtt server I currently have no way of communicating with the board.

**Comment by Jaimi5** [comment]
Hi @JDMarc I am working again to add the Chat into the code and trying to configure the arduino to enable bluetooth and wifi at the same time. Hope this week I can update you with new information!

**Comment by Jaimi5** [comment]
Now it should work correctly!
